Repository Voidustries/Poly, pull requests merged in 2018-04, with the labels that each got.

#22 Adoption of a proper workflow into Poly
  .circleci/config.yml
  Poly.iml
  README.md
  build.gradle
  src/main/java/com/voidustries/poly/Main.java
  src/main/java/com/voidustries/poly/PolySplash.java
  src/main/java/com/voidustries/poly/Settings.java
  src/main/java/com/voidustries/poly/SysTray.java
  src/main/java/com/voidustries/poly/conection/AbstractAgent.java
  src/main/java/com/voidustries/poly/conection/HttpRequestHandler.java
  src/main/java/com/voidustries/poly/conection/tvdb/TVDB.java
  src/main/java/com/voidustries/poly/gui/Controller.java
  src/main/java/com/voidustries/poly/gui/GUI.java
  src/main/resources/com/voidustries/poly/Icon.png
  src/main/resources/com/voidustries/poly/gui/Icon.png
  src/main/resources/com/voidustries/poly/gui/layoutForm.fxml
  src/main/resources/com/voidustries/poly/splash.gif
  src/test/java/com/voidustries/poly/MainTest.java
  src/test/java/com/voidustries/poly/conection/HttpRequestHandlerTest.java
Labels: enhancement

#24 Feature/pretty readme
  README.md
Labels: enhancement

#26 Hotfix for CircleCI badge
  README.md
Labels: bug, hotfix

#29 Update README.md
  README.md
Labels: hotfix
